    [theme]
    primaryColor ='#7792E3'
    backgroundColor ='#f5f5f5'
    secondaryBackgroundColor ='#B9F1C0'
    textColor='#262730'
    font ='sans serif'

    logging_file:str="streamlit_logs.log"
